version: '3'

services:
  zookeeper-1:
    image: zookeeper:3.5.8
    restart: always
    hostname: zookeeper-1
    container_name: zookeeper-1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - ./zookeeper-1/data:/data
      - ./zookeeper-1/logs:/datalog

  zookeeper-2:
    image: zookeeper:3.5.8
    restart: always
    hostname: zookeeper-2
    container_name: zookeeper-2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888
    volumes:
      - ./zookeeper-2/data:/data
      - ./zookeeper-2/logs:/datalog

  zookeeper-3:
    image: zookeeper:3.5.8
    restart: always
    hostname: zookeeper-3
    container_name: zookeeper-3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888
    volumes:
      - ./zookeeper-3/data:/data
      - ./zookeeper-3/logs:/datalog

  kafka-1:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT:/0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka-2:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:909
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:909
